### ISSUE TITLE
 Conversion from mono12packed without grabResult (using raw bytes)

### ISSUE THREAD

**Issue by Niv-R** [basler/pypylon-samples#8]
**Use Case**
My use case can benefit from performing the conversion from mono12packed in another Python process.

**Problem**
I've attempted to use ImageFormatConverter.Convert, and the docstring details the parameters as follows:
```python
"""
Parameters
        ----------
        * `pDestinationBuffer` :  
            The pointer to the buffer of the destination image.  
        * `destinationBufferSizeBytes` :  
            The size of the buffer of the destination image.  
        * `pSourceBuffer` :  
            The pointer to the buffer of the source image.  
        * `sourceBufferSizeBytes` :  
            The size of the buffer of the source image.  
        * `sourcePixelType` :  
            The pixel type of the source image.  
        * `sourceWidth` :  
            The number of pixels in a row in the source image.  
        * `sourceHeight` :  
            The number of rows in the source image.  
        * `sourcePaddingX` :  
            The number of extra data bytes at the end of each row. The default value is
            usually 0.  
        * `sourceOrientation` :  
            The vertical orientation of the source image in the image buffer. The
            default value is usually ImageOrientation_TopDown. 
"""
```

However, the method actually expects a PylonImage object, as indicated by the following error message:

```Wrong number or type of arguments for overloaded function 'ImageFormatConverter_Convert'.
  Possible C/C++ prototypes are:
    Pylon::CImageFormatConverter::Convert(Pylon::IReusableImage &,Pylon::IImage const &)
    Pylon::CImageFormatConverter::Convert(Pylon::IReusableImage &,Pylon::CGrabResultPtr const &)
```

**Attempted Solution**
I tried converting my bytes to a PylonImage using:

```
image = pylon.PylonImage()
image.AttachUserBuffer(...)
```

However, AttachUserBuffer failed with the same error regardless of the arguments provided:

```
    return _pylon.PylonImage_AttachUserBuffer(self, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Wrong number or type of arguments for overloaded function 'PylonImage_AttachUserBuffer'.
  Possible C/C++ prototypes are:
    Pylon::CPylonImage::AttachUserBuffer(void *,size_t,Pylon::EPixelType,uint32_t,uint32_t,size_t,Pylon::EImageOrientation,CPylonImageUserBufferEventHandler *)
    Pylon::CPylonImage::AttachUserBuffer(void *,size_t,Pylon::EPixelType,uint32_t,uint32_t,size_t,Pylon::EImageOrientation)
    Pylon::CPylonImage::AttachUserBuffer(void *,size_t,Pylon::EPixelType,uint32_t,uint32_t,size_t)
```

**Question**
Is it possible to use Pylon's conversion on a raw buffer instead of a grabResult? If so, how can this be achieved?

**Comment by HighImp** [comment]
Hi, 
can you please try the latest version from today? 
There was a bugfix for the user buffer attachment. 

If you still have the problem, please use the [pypylon-issue](https://github.com/basler/pypylon/issues) room, 
as this is for the samples. 
Best regards!

**Comment by Niv-R** [comment]
> Hi, can you please try the latest version from today? There was a bugfix for the user buffer attachment.
> 
> If you still have the problem, please use the [pypylon-issue](https://github.com/basler/pypylon/issues) room, as this is for the samples. Best regards!

Understood, I was able to confirm the new methods added in pylon 4.1.0 to replace `AttachUserBuffer` work.
