### ISSUE TITLE
Grab 1 image every 60 seconds for about 150 minutes

### ISSUE THREAD

**Issue by astraloby** [basler/pypylon-samples#9]
Hello, good afternoon. I have in my possession a BASLER camera model acA640-750um and I want to create a code that allows me to take a picture every 60 seconds over a period of about 150 minutes. I had a code that a student gave me, but it didn't work because after a while an error occurs and the code stops without saving any images. That's why I would like to save each image as they are captured. Is it possible? I would greatly appreciate any help or tips. 

The line of code i was having issue was:

`grabResult = cameras.RetrieveResult(600000000, pylon.TimeoutHandling_ThrowException)`

I set up a really high number because originally was 5000 and i thought that could be the issue.

**Comment by thiesmoeller** [comment]
60 Seconds will be larger than the max frameperiod of your camera..
So easiest will be to issue a sw Trigger ever 60 Seconds

**Comment by astraloby** [comment]
You are right @thiesmoeller thank you for the advice. This is the code that worked for me : 

<img width="859" alt="image" src="https://github.com/basler/pypylon-samples/assets/163364756/978140b3-a50e-49e9-91bf-9d89c59bc036">

It is effectively taking a picture every 60 seconds.

**Comment by thiesmoeller** [comment]
Yes this works. 
In your Code the camera captures all the time and you "Pick" the latest image every 60s.

**Comment by astraloby** [comment]
Thank you again @thiesmoeller. It is my first time using the camera, do you know if making the camera capture all the time (as in my code) deteriorates its functionality over time? At first I thought it would be inefficient or even more damaging to stop the camera and open it every 60 seconds. For now I only notice that the camera heats a bit (I think its normal), but it has a little heatsink as shown in the picture below:

![E3D5A13A-BC1C-4694-9B76-C88B7ECBA382](https://github.com/basler/pypylon-samples/assets/163364756/8e1d2513-a987-4726-980a-3b17fce5fb35)

Would you recommend changing my code or any other tips? I would greatly appreciate any advice :)

**Comment by thiesmoeller** [comment]
Running always is not a problem. Basler cameras are designed to run 24/7 for years without stop.

One proposal to be more efficient is to use software trigger. The capture engine is always active but the camera will wait for your command to capture one frame.

see this example code:

```python
import os
import cv2
from pypylon import pylon as py
from pypylon import genicam
import time


def main():
    capture_limit = 150
    capture_period_s = 1

    os.makedirs("img", exist_ok=True)

    camera = py.InstantCamera(py.TlFactory.GetInstance().CreateFirstDevice())
    camera.Open()
    camera.ExposureTime.SetValue(10000)
    camera.TriggerMode.SetValue("On")  # Enable trigger mode
    camera.TriggerSource.SetValue("Software")  # Set trigger source to software
    camera.StartGrabbing(py.GrabStrategy_LatestImageOnly)

    try:
        capture_count = 0
        last_capture_time = time.time()
        last_camera_time = None

        while capture_count < capture_limit:
            current_time = time.time()
            if (
                current_time - last_capture_time >= capture_period_s
                or capture_count == 0
            ):
                # Execute software trigger
                camera.TriggerSoftware.Execute()

                # Retrieve and handle the grab result using a context manager
                with camera.RetrieveResult(
                    5000, py.TimeoutHandling_ThrowException
                ) as grabResult:
                    if grabResult.GrabSucceeded():
                        image = grabResult.Array
                        filename = f"img/image_{capture_count + 1}.png"
                        cv2.imwrite(filename, image)

                        # measure real time
                        if last_camera_time == None:
                            last_camera_time = grabResult.TimeStamp
                            delta_time = 0
                        else:
                            delta_time = grabResult.TimeStamp - last_camera_time
                            last_camera_time = grabResult.TimeStamp

                        print(f"Imagen guardada: {filename} , period { delta_time / 1.e9 }")
                        capture_count += 1
                        last_capture_time = current_time

                        cv2.imshow("Basler Camera", image)

            # Allow breaking the loop by pressing 'q'
            if cv2.waitKey(1) & 0xFF == ord("q"):
                print("Stopped by user")
                break

    except genicam.GenericException as e:
        print(f"Error: {e}")

    camera.StopGrabbing()
    camera.Close()
    cv2.destroyAllWindows()


if __name__ == "__main__":
    main()
```

**Comment by astraloby** [comment]
@thiesmoeller Impressive! Those little cameras are really powerful. I just tested the code and it works like a charm. I also now understand more about the cameras and how they work so thank you very much Sir, hope you have a great day 👍
